### ISSUE TITLE
您好，请问文章的访问量为什么一直是0呢

### ISSUE THREAD

**Issue by angleHan** [chiperman/gridea-theme-xiaox#1]

**Comment by chiperman** [comment]
你先去 leancloud 里面看看有没有创建一个 count class，如果没有先创建一个。
可以参考这个文档进行排查和部署。[官方文档](https://valine.js.org/visitor.html)

**Comment by angleHan** [comment]
您好，我看了有counter这个class，是不是名字要一致？------------------ 原始邮件 ------------------
发件人: "chipermanju"<notifications@github.com>
发送时间: 2020年5月15日(星期五) 中午11:43
收件人: "chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com>;
抄送: "angleHan"<844417048@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chiperman/gridea-theme-xiaox] 您好，请问文章的访问量为什么一直是0呢 (#1)




 
你先去 leancloud 里面看看有没有创建一个 count class，如果没有先创建一个。
 
&mdash;

**Comment by chiperman** [comment]
![image](https://user-images.githubusercontent.com/34889778/82011230-eb060800-96a6-11ea-8e30-76009982b759.png)
应该是有一个这样子的类，并且能够显示出你每个url的具体信息

**Comment by chiperman** [comment]
麻烦你把你的博客地址发一下，我帮你看看

**Comment by angleHan** [comment]
感谢回复，我的博客地址是dreamfixer.top------------------ 原始邮件 ------------------
发件人: "chipermanju"<notifications@github.com>
发送时间: 2020年5月15日(星期五) 中午12:24
收件人: "chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com>;
抄送: "angleHan"<844417048@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chiperman/gridea-theme-xiaox] 您好，请问文章的访问量为什么一直是0呢 (#1)




 
麻烦你把你的博客地址发一下，我帮你看看
 
&mdash;

**Comment by angleHan** [comment]
我也有一个Counter子类，在原来的主题里可以用，但是换成您的就不能用了------------------ 原始邮件 ------------------
发件人: "chipermanju"<notifications@github.com>
发送时间: 2020年5月15日(星期五) 中午12:24
收件人: "chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com>;
抄送: "angleHan"<844417048@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chiperman/gridea-theme-xiaox] 您好，请问文章的访问量为什么一直是0呢 (#1)




 

 应该是有一个这样子的类，并且能够显示出你每个url的具体信息
 
&mdash;

**Comment by chiperman** [comment]
刚才查看了你的网页源码，我想我可能找到原因了。
`https://dreamfixer.top/post/qi-yi-zhi-fen-jie-yu-te-zheng-zhi-fen-jie-de-li-jie/
`
你的网页URL前缀有`/post/`，而你的网页
![image](https://user-images.githubusercontent.com/34889778/82011504-c2324280-96a7-11ea-9396-a40e333c1048.png)却没有`/post/`的前缀，所以有两个解决办法。
第一个是去`HTML`的源码里面的`<span id="/post/"`>加上`/post/`。
或者去 Gridea 设置里面勾选
![image](https://user-images.githubusercontent.com/34889778/82011639-2a812400-96a8-11ea-801f-a5c1f8438a85.png)

**Comment by angleHan** [comment]
非常感谢，我会尝试您的解决办法。 祝好！------------------ 原始邮件 ------------------
发件人: "chipermanju"<notifications@github.com>
发送时间: 2020年5月15日(星期五) 中午12:33
收件人: "chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com>;
抄送: "angleHan"<844417048@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chiperman/gridea-theme-xiaox] 您好，请问文章的访问量为什么一直是0呢 (#1)




 
刚才查看了你的网页源码，我想我可能找到原因了。
 https://dreamfixer.top/post/qi-yi-zhi-fen-jie-yu-te-zheng-zhi-fen-jie-de-li-jie/ 你的网页URL前缀有/post/，而你的网页
 却没有/post/的前缀，所以有两个解决办法，第一个是去HTML的源码里面的<span id="/post/">加上/post/，或者去 Gridea 设置里面勾选
 
 
&mdash;

**Comment by chiperman** [comment]
如果解决麻烦告知一下，这个是我这边自己修改后导致和 Gridea 默认设置出现了冲突。

**Comment by angleHan** [comment]
好的，一定------------------ 原始邮件 ------------------
发件人: "chipermanju"<notifications@github.com>
发送时间: 2020年5月15日(星期五) 中午12:42
收件人: "chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com>;
抄送: "angleHan"<844417048@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chiperman/gridea-theme-xiaox] 您好，请问文章的访问量为什么一直是0呢 (#1)




 
如果解决麻烦告知一下，这个是我这边自己修改后导致和 Gridea 默认设置出现了冲突。
 
&mdash;

**Comment by angleHan** [comment]
将文章URL路径改为精简后，问题解决！


感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chipermanju"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月15日(星期五) 中午12:42
收件人:&nbsp;"chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com&gt;;
抄送:&nbsp;"hjl"<844417048@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chiperman/gridea-theme-xiaox] 您好，请问文章的访问量为什么一直是0呢 (#1)





 
如果解决麻烦告知一下，这个是我这边自己修改后导致和 Gridea 默认设置出现了冲突。
