### ISSUE TITLE
博主看过来，我貌似又发现一个bug。

### ISSUE THREAD

**Issue by angleHan** [chiperman/gridea-theme-xiaox#2]
就是在主页点击加载更多后，一直显示不出来（一直提示正在努力加载），不知道是什么原因

**Comment by chiperman** [comment]
![image](https://user-images.githubusercontent.com/34889778/82205925-e9a03e00-9939-11ea-875d-0493f5884edc.png)
你根据报错的提示找一下有没有相关的资料

**Comment by angleHan** [comment]
ok------------------ 原始邮件 ------------------
发件人: "chipermanju"<notifications@github.com>
发送时间: 2020年5月18日(星期一) 晚上7:01
收件人: "chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com>;
抄送: "angleHan"<844417048@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chiperman/gridea-theme-xiaox] 博主看过来，我貌似又发现一个bug。 (#2)




 

 你根据报错的提示找一下有没有相关的资料
 
&mdash;

**Comment by angleHan** [comment]
大佬，您方便把您gridea里主题的基础配置发过来我参考一下吗，我看了网上的不太懂，，感觉应该是基础配置的问题------------------ 原始邮件 ------------------
发件人: "chipermanju"<notifications@github.com>
发送时间: 2020年5月18日(星期一) 晚上7:01
收件人: "chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com>;
抄送: "angleHan"<844417048@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chiperman/gridea-theme-xiaox] 博主看过来，我貌似又发现一个bug。 (#2)




 

 你根据报错的提示找一下有没有相关的资料
 
&mdash;

**Comment by chiperman** [comment]
如图：
![image](https://user-images.githubusercontent.com/34889778/82208083-7e586b00-993d-11ea-83e1-097ac9749b75.png)
你可以去官方群里面问下其他用户，有没有遇到这个情况的，因为我没有遇到过，目前还不知道解决办法。

**Comment by chiperman** [comment]
你也可以尝试一下重新上传同步到 Github repo 里面。

**Comment by angleHan** [comment]
好的，无论如何，谢谢！------------------ 原始邮件 ------------------
发件人: "chipermanju"<notifications@github.com>
发送时间: 2020年5月18日(星期一) 晚上7:28
收件人: "chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com>;
抄送: "angleHan"<844417048@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chiperman/gridea-theme-xiaox] 博主看过来，我貌似又发现一个bug。 (#2)




 
你也可以尝试一下重新上传同步到 Github repo 里面。
 
&mdash;

**Comment by chiperman** [comment]
没事儿，我也没帮到什么，如果你找到了解决办法你可以分享一下，万一有人遇到了同样的问题可以参考。

**Comment by angleHan** [comment]
大佬，您能再帮我看看博客吗，，我也没改什么，，但是现在又出了一个新的错误，访问量又不显示了。。------------------ 原始邮件 ------------------
发件人: "chipermanju"<notifications@github.com>
发送时间: 2020年5月18日(星期一) 晚上7:32
收件人: "chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com>;
抄送: "angleHan"<844417048@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chiperman/gridea-theme-xiaox] 博主看过来，我貌似又发现一个bug。 (#2)




 
没事儿，我也没帮到什么，如果你找到了解决办法你可以分享一下，万一有人遇到了同样的问题可以参考。
 
&mdash;

**Comment by angleHan** [comment]
只是电脑端的chrome不能显示，其它平台还可以------------------ 原始邮件 ------------------
发件人: "chipermanju"<notifications@github.com>
发送时间: 2020年5月18日(星期一) 晚上7:32
收件人: "chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com>;
抄送: "angleHan"<844417048@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chiperman/gridea-theme-xiaox] 博主看过来，我貌似又发现一个bug。 (#2)




 
没事儿，我也没帮到什么，如果你找到了解决办法你可以分享一下，万一有人遇到了同样的问题可以参考。
 
&mdash;

**Comment by chiperman** [comment]
跟你没关系，怀疑是 Leancloud 出了问题。
![image](https://user-images.githubusercontent.com/34889778/82209387-c8425080-993f-11ea-90c8-e58200d6a054.png)
我的博客目前也是无法显示阅读量，而你手机能显示应该是缓存没有清理掉，电脑已经刷新了。

**Comment by angleHan** [comment]
ok，谢谢啦------------------ 原始邮件 ------------------
发件人: "chipermanju"<notifications@github.com>
发送时间: 2020年5月18日(星期一) 晚上7:43
收件人: "chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com>;
抄送: "angleHan"<844417048@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chiperman/gridea-theme-xiaox] 博主看过来，我貌似又发现一个bug。 (#2)




 
跟你没关系，怀疑是 Leancloud 出了问题。
 
 我的博客目前也是无法显示阅读量，而你手机能显示应该是缓存没有清理掉，电脑已经刷新了。
 
&mdash;

**Comment by angleHan** [comment]
大佬，我觉得这个错误是不是因为代码里AV这个变量没有声明成全局变量，然后浏览器不识别导致的。


因为我看leancloud端数据记录还是正常的。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chipermanju"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 晚上7:43
收件人:&nbsp;"chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com&gt;;
抄送:&nbsp;"hjl"<844417048@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chiperman/gridea-theme-xiaox] 博主看过来，我貌似又发现一个bug。 (#2)





 
跟你没关系，怀疑是 Leancloud 出了问题。
 
 我的博客目前也是无法显示阅读量，而你手机能显示应该是缓存没有清理掉，电脑已经刷新了。

**Comment by chiperman** [comment]
有可能是因为 Valine 更新了，因为现在是评论没有，有可能是他们那边改变了需要的参数什么的。所以导致评论消失，而阅读量也是通过 Valine 来读取 Leancloud 的数据。

**Comment by angleHan** [comment]
明白了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chipermanju"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 上午10:12
收件人:&nbsp;"chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com&gt;;
抄送:&nbsp;"hjl"<844417048@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chiperman/gridea-theme-xiaox] 博主看过来，我貌似又发现一个bug。 (#2)





 
有可能是因为 Valine 更新了，因为现在是评论没有，有可能是他们那边改变了需要的参数什么的。所以导致评论消失，而阅读量也是通过 Valine 来读取 Leancloud 的数据。

**Comment by chiperman** [comment]
阅读量已经恢复正常

**Comment by angleHan** [comment]
收到了，一切正常，谢谢你。------------------ 原始邮件 ------------------
发件人: "chipermanju"<notifications@github.com>
发送时间: 2020年5月20日(星期三) 中午11:05
收件人: "chiperman/gridea-theme-xiaox"<gridea-theme-xiaox@noreply.github.com>;
抄送: "angleHan"<844417048@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chiperman/gridea-theme-xiaox] 博主看过来，我貌似又发现一个bug。 (#2)




 
阅读量已经恢复正常
 
&mdash;
